/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author patri
 */
public class FrmEjemploRadioButton extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjemploRadioButton
     */
    public FrmEjemploRadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEstadoCivil = new javax.swing.ButtonGroup();
        chkHobbyFutbol = new javax.swing.JCheckBox();
        chkHobbyPadel = new javax.swing.JCheckBox();
        chkHobbyGamer = new javax.swing.JCheckBox();
        chkHobbyBasket = new javax.swing.JCheckBox();
        rdoCasado = new javax.swing.JRadioButton();
        rdoAUC = new javax.swing.JRadioButton();
        rdoSoltero = new javax.swing.JRadioButton();
        rdoDivorciado = new javax.swing.JRadioButton();
        rdoViudo = new javax.swing.JRadioButton();
        btnMostrar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chkHobbyFutbol.setText("Futbol");

        chkHobbyPadel.setText("Padel");

        chkHobbyGamer.setText("Gamer");

        chkHobbyBasket.setText("Basket");

        bgEstadoCivil.add(rdoCasado);
        rdoCasado.setText("Casado");
        rdoCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCasadoActionPerformed(evt);
            }
        });

        bgEstadoCivil.add(rdoAUC);
        rdoAUC.setText("AUC");
        rdoAUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAUCActionPerformed(evt);
            }
        });

        bgEstadoCivil.add(rdoSoltero);
        rdoSoltero.setText("Soltero");
        rdoSoltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSolteroActionPerformed(evt);
            }
        });

        bgEstadoCivil.add(rdoDivorciado);
        rdoDivorciado.setText("Divorciado");
        rdoDivorciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDivorciadoActionPerformed(evt);
            }
        });

        bgEstadoCivil.add(rdoViudo);
        rdoViudo.setText("Viudo");
        rdoViudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoViudoActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        jLabel1.setText("Hobby");

        jLabel2.setText("Estado civil");

        jLabel3.setText("Nombre pareja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkHobbyFutbol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkHobbyPadel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkHobbyGamer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkHobbyBasket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrar)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoCasado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoAUC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoSoltero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoDivorciado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoViudo))
                                    .addComponent(txtNombre))
                                .addGap(18, 18, 18)
                                .addComponent(btnVer)))
                        .addGap(0, 84, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHobbyFutbol)
                    .addComponent(chkHobbyPadel)
                    .addComponent(chkHobbyGamer)
                    .addComponent(chkHobbyBasket)
                    .addComponent(btnMostrar))
                .addGap(92, 92, 92)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCasado)
                    .addComponent(rdoAUC)
                    .addComponent(rdoSoltero)
                    .addComponent(rdoDivorciado)
                    .addComponent(rdoViudo)
                    .addComponent(btnVer))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        
        if(rdoCasado.isSelected())
            JOptionPane.showMessageDialog(this, "Ud esta casado");
        else if(rdoAUC.isSelected())
            JOptionPane.showMessageDialog(this, "Ud esta Con Acuerdo Unión Civil");
        else if(rdoSoltero.isSelected())
            JOptionPane.showMessageDialog(this, "Ud esta Soltero");
        else if(rdoDivorciado.isSelected())
            JOptionPane.showMessageDialog(this, "Ud esta Divorciado");
        else if(rdoViudo.isSelected())
            JOptionPane.showMessageDialog(this, "Ud esta Viudo");
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void rdoCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCasadoActionPerformed
        // TODO add your handling code here:
        txtNombre.setEditable(true);
    }//GEN-LAST:event_rdoCasadoActionPerformed

    private void rdoSolteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSolteroActionPerformed
        // TODO add your handling code here:
        txtNombre.setEditable(false);
        txtNombre.setText("");
    }//GEN-LAST:event_rdoSolteroActionPerformed

    private void rdoAUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAUCActionPerformed
        // TODO add your handling code here:
        txtNombre.setEditable(true);
    }//GEN-LAST:event_rdoAUCActionPerformed

    private void rdoDivorciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDivorciadoActionPerformed
        // TODO add your handling code here:
        txtNombre.setEditable(true);
    }//GEN-LAST:event_rdoDivorciadoActionPerformed

    private void rdoViudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoViudoActionPerformed
        // TODO add your handling code here:
        txtNombre.setEditable(true);
    }//GEN-LAST:event_rdoViudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjemploRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEstadoCivil;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVer;
    private javax.swing.JCheckBox chkHobbyBasket;
    private javax.swing.JCheckBox chkHobbyFutbol;
    private javax.swing.JCheckBox chkHobbyGamer;
    private javax.swing.JCheckBox chkHobbyPadel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rdoAUC;
    private javax.swing.JRadioButton rdoCasado;
    private javax.swing.JRadioButton rdoDivorciado;
    private javax.swing.JRadioButton rdoSoltero;
    private javax.swing.JRadioButton rdoViudo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
